### ISSUE TITLE
Error in auto compile caffe

### ISSUE THREAD

**Issue by overfitttting** [CMU-Perceptual-Computing-Lab/openpose_train#10]
hi, gines, thank you for your great work.

when I try to run the `make all -j32 && make pycaffe -j32` I get the following error:
`make: *** No rule to make target 'all'. Stop.`

and I found there is one folder autocompile. I change the some config parameters, but some parameters are hard to understand. and I think it lead to the error.

`------------------------- Installing Caffe -------------------------
NOTE: This script assumes that CUDA and cuDNN are already installed on your machine. Otherwis
------------------------- Checking Ubuntu Version -------------------------
Ubuntu Release: 16.04
------------------------- Ubuntu Version Checked -------------------------

------------------------- Compiling Caffe -------------------------
CXX .build_release/src/caffe/proto/caffe.pb.cc
CXX src/caffe/parallel.cpp
CXX src/caffe/openpose/dataAugmentation.cpp
CXX src/caffe/openpose/oPDataTransformer.cpp
CXX src/caffe/openpose/layers/oPVideoLayer.cpp
CXX src/caffe/openpose/layers/oPDataLayer.cpp
CXX src/caffe/openpose/metaData.cpp
CXX src/caffe/syncedmem.cpp
CXX src/caffe/blob.cpp
CXX src/caffe/util/benchmark.cpp
CXX src/caffe/util/db.cpp
CXX src/caffe/util/insert_splits.cpp
CXX src/caffe/util/db_lmdb.cpp
CXX src/caffe/util/upgrade_proto.cpp
CXX src/caffe/util/signal_handler.cpp
CXX src/caffe/util/im2col.cpp
CXX src/caffe/util/hdf5.cpp
CXX src/caffe/util/math_functions.cpp
CXX src/caffe/util/blocking_queue.cpp
CXX src/caffe/util/io.cpp
CXX src/caffe/util/cudnn.cpp
CXX src/caffe/util/db_leveldb.cpp
CXX src/caffe/layer_factory.cpp
CXX src/caffe/layer.cpp
CXX src/caffe/layers/contrastive_loss_layer.cpp
src/caffe/openpose/oPDataTransformer.cpp:2:37: fatal error: opencv2/core/core.hpp: No such fi
compilation terminated.
src/caffe/openpose/layers/oPDataLayer.cpp:2:33: fatal error: opencv2/core/core.hpp: No such f
compilation terminated.
In file included from src/caffe/syncedmem.cpp:1:0:
./include/caffe/common.hpp:4:32: fatal error: boost/shared_ptr.hpp: No such file or directory
compilation terminated.
src/caffe/openpose/dataAugmentation.cpp:1:30: fatal error: opencv2/opencv.hpp: No such file o
compilation terminated.
Makefile:600: recipe for target '.build_release/src/caffe/openpose/oPDataTransformer.o' faile
CXX src/caffe/layers/cudnn_softmax_layer.cpp
make: *** [.build_release/src/caffe/openpose/oPDataTransformer.o] Error 1
make: *** Waiting for unfinished jobs....
Makefile:600: recipe for target '.build_release/src/caffe/openpose/layers/oPDataLayer.o' fail
make: *** [.build_release/src/caffe/openpose/layers/oPDataLayer.o] Error 1
Makefile:600: recipe for target '.build_release/src/caffe/syncedmem.o' failed
make: *** [.build_release/src/caffe/syncedmem.o] Error 1`

I didn't attach all error report.
some portion in config is hard to understand such as
`# With new NCLL2
INCLUDE_DIRS += /home/gines/devel/nccl/build/include/
LIBRARY_DIRS += /home/gines/devel/nccl/build/lib/
LIBRARY_DIRS += /usr/lib/x86_64-linux-gnu/
INCLUDE_DIRS := $(PYTHON_INCLUDE) /usr/local/include /usr/include/hdf5/serial
LIBRARY_DIRS := $(PYTHON_LIB) /usr/local/lib /usr/lib /usr/lib/x86_64-linux-gnu /usr/lib/x86_64-linux-gnu/hdf5/serial`
Does it mean I should install a nccl and hdf5 and find it path, then add it here?

**Comment by gineshidalgo99** [comment]
It seems that opencv and boost are not found, did you installed them? It's Caffe, so please, check the official Caffe instructions for installation and its trouble-shooting guid for more details, it can be compiled in the exact same way.
