### ISSUE TITLE
How to set "sProbabilityOnlyBackground" ?

### ISSUE THREAD

**Issue by 491913145** [CMU-Perceptual-Computing-Lab/openpose_train#11]
I downloaded 'lmdb_coco' and 'lmdb_background' dataset, and would like to train COCO_18 model. what should i set on "sProbabilityOnlyBackground"? And is it right to set sBodyParts=18?

**Comment by gineshidalgo99** [comment]
sProbabilityOnlyBackground should be 0.01-0.05, depending on how much you want to avoid false positives.

**Comment by 491913145** [comment]
thank you!
