### ISSUE TITLE
person_keypoints_train2017_foot_v1 and person_keypoints_val2017_foot_v1 do not follow the same structure

### ISSUE THREAD

**Issue by emredog** [CMU-Perceptual-Computing-Lab/openpose_train#16]
Annotation file for the training has 23 keypoints for each annotation, so it is a self-contained B25 annotation; whereas the validation file has 6 keypoints. I can load the validation file along with the coco one (17 joints), they complement each other.

Why both do not follow the same structure? Is there a specific reason for this? 

Thanks.

**Comment by Galaxies99** [comment]
I have the same confusion, too.

BTW, the code 'train/a2_coco_jsonToMat.m' will cause an assertion failure, if I don't modify the code to load along with original data (when running foot validation data).

**Comment by gineshidalgo99** [comment]
Yes, validation "only" includes the 6 foot keypoints, so it can validate "only" those keypoints. Training includes also body, so everything can be trained together. Sorry for the confusion.
