### ISSUE TITLE
can you share the training code for "lmdb_hand_dome" and "lmdb_hand_mpii" dataset?

### ISSUE THREAD

**Issue by huangshaoguang** [CMU-Perceptual-Computing-Lab/openpose_train#19]
Hello! Thank you for your great and general share! Can you share the training code for "lmdb_hand_dome" and "lmdb_hand_mpii" dataset? I really want to train the hand model but I can't allways get the caffe code.  Thank you for advance!

**Comment by gineshidalgo99** [comment]
Those are included on this repo. BODY_135 uses them.
