### ISSUE TITLE
Attempting to download the lmdb data fails with 404

### ISSUE THREAD

**Issue by QUJIJI** [CMU-Perceptual-Computing-Lab/openpose_train#21]
Running cd training && bash a_downloadAndUpzipLmdbs.sh fails with 404.

**Comment by tingz2004** [comment]
https://github.com/CMU-Perceptual-Computing-Lab/openpose_train/issues/23#issuecomment-570247676

**Comment by QUJIJI** [comment]
Thanks for your help!@tingz2004
