### ISSUE TITLE
Can‘t Download the LMDB files 

### ISSUE THREAD

**Issue by MikeEnvi** [CMU-Perceptual-Computing-Lab/openpose_train#23]
When  I download the LMDB files ready to be used by running cd training && bash a_downloadAndUpzipLmdbs.sh. the errors show  404 Not Found for each link

**Comment by tingz2004** [comment]
You can fix few things in a_downloadAndUpzipLmdbs.sh:
1. the url part of each wget command are missing '/' on the last path. e.g.  ${OPENPOSE_TRAINING_URL}${DATASET_DIR}data.mdb
should be
${OPENPOSE_TRAINING_URL}${DATASET_DIR}/data.mdb
2. The DATASET_DIR=lmdb_coco2017 should be
DATASET_DIR=lmdb_coco

**Comment by zhongxiaofang-run** [comment]
thank you , I have  done it

**Comment by breezepwy** [comment]
I cannot connect to these CMU's links in a_downloadAndUpzipLmdbs.sh, but I can access the CMU's website. And it shows 502 BAD GATEWAY. Is there anything wrong with my network? Hope for some help!

**Comment by gineshidalgo99** [comment]
It should be working now, sorry!
