### ISSUE TITLE
About "jsonencode" function is undefined

### ISSUE THREAD

**Issue by MikeEnvi** [CMU-Perceptual-Computing-Lab/openpose_train#24]
Hi , I meet a error when I run "a1_coco_jsonToNegativeJson.m" script in matlab.  The error shows "Undefined function 'jsonencode ' "  . line 69 :  jsonString=jsonencode(imagesPaths)  .  My matlab is matlab2014a

**Comment by zhongxiaofang-run** [comment]
you need install at least Matlab2016

**Comment by gineshidalgo99** [comment]
Yes, unfortunately jsonencode is from 2016 onwards.
