### ISSUE TITLE
What kind GPU is required to run the training?

### ISSUE THREAD

**Issue by tingz2004** [CMU-Perceptual-Computing-Lab/openpose_train#27]
I followed the training/README.md file to build the code on the Ubuntu box which has 1 GPU Quadro RTX 5000 with 16GB memory. But the running "bash train_pose.sh 0" reported "error == cudaSuccess (2 vs. 0)  out of memory".
What kind GPU is required to run the training?
Is there a way to work around it?

Thanks!

**Comment by tingz2004** [comment]
I lower the batch size to be 4 from 10, the issue is resolved.

**Comment by arvkr** [comment]
I was facing the same problem, thanks!

**Comment by FreshlyBrewedCode** [comment]
Running a RTX 3070 with 8GB memory for some local testing. Using the default settings the training would just be stuck at the first iteration. I modified line 70 in `d_setLayers.py` to:
```python
 sBatchSizes = [4]
```
after that training would finally run at about 15s/20 iter.
