### ISSUE TITLE
Trainning Errror

### ISSUE THREAD

**Issue by MikeEnvi** [CMU-Perceptual-Computing-Lab/openpose_train#29]
Hello. I have meet a problem that can't be solved by myself. Please help me.
I want just train model as origin model that output 18 points of body.
First, I have generated the COCO dataset LMDB files(without foot、hand、face dataset) by myself followed your step descriped at /Train/README.md.
I modified the c_generateLmdbs.py file by uncommented line 136 and line 164， other code not modified.

Second, I have finished complied Caffe. Runing script file generateProtoTxt.py generate the Caffe ProtoTxt . I modified generateProtoTxt.py follow README.md, set sAddFoot=0,sAddMpii=0, sAddFace=0 and sAddHands=0,sAddDome=0,sProbabilityOnlyBackground=0, sSuperModel=0,.

my pose_trianing.prototxt is like this:(data layer)

layer {
name: "image"
type: "OPData"
top: "image"
top: "label"
data_param {
batch_size: 10
backend: LMDB
}
op_transform_param {
stride: 8
max_rotate_degree: 45
crop_size_x: 368
crop_size_y: 368
center_perterb_max: 40.0
center_swap_prob: 0.0
scale_prob: 1.0
scale_min: 0.333333333
scale_max: 1.5
target_dist: 0.6
number_max_occlusions: 2
sigmas: "7.0"
model: "COCO_17;COCO_17_17"
source_background: "/mnt/zhong/openpose_train/dataset/lmdb_background"
source: "/mnt/zhong/openpose_train/dataset/lmdb_coco"
media_directory:""
normalization: 0
add_distance: false
}
}

Error:
I run the comand "bash train_pose.sh”. Meet next error:
terminate called after throwing an instance of 'std::runtime_error'
what(): Error: mSources.size()!=nModels.size() at 56, OPDatalayer. src/caffe/openpose/layers/oPDatalayer.cpp
*** Aborted at 1581070034(unix time ) try "data -d @1581070034" if you are using GUN data ***
.....

Does it only train model which output 25 points (Body+ Foot)? Can't train model which output 18 points(Body) as origin openPose?

**Comment by gineshidalgo99** [comment]
You said model is COCO_17, so it is expecting 17 body keypoints. Change to the other models for higher number of keypoints.

**Comment by DeepBehavier** [comment]
I have the same problem. waitting for help

**Comment by DeepBehavier** [comment]
sAddFoot =sAddMpii=sAddFace=sAddHands=sAddDome=0

**Comment by tommarz** [comment]
I have the same problem as well. I am trying to train my model only on body (sAddFoot =sAddMpii=sAddFace=sAddHands=sAddDome=0) with the lmdb body coco dataset I generated by running a_lmdbGetBody.sh .
Do I have to train on more than 17 keypoints? (e.g set sAddFoot=1 for example)

**Comment by chensonglu** [comment]
I solve it by modifying 17 to 18 in line 57 and the model should be COCO_18.

**Comment by akhalili** [comment]
Hi All, I am getting the following error:
I0528 23:06:38.117194   164 layer_factory.hpp:77] Creating layer image
terminate called after throwing an instance of 'std::runtime_error'
  what():  Error: mSources.size() != mModels.size() at 54, OPDataLayer, src/caffe/openpose/layers/oPDataLayer.cpp
  
 any idea? I printed the size of mSources() and mModels.size() there are 1 and 2 in respective. 
 
 
I also did  

set sAddFoot=0,sAddMpii=0, sAddFace=0 and sAddHands=0,sAddDome=0

Here is the first layers:
 
 layer {
  name: "image"
  type: "OPData"
  top: "image"
  top: "label"
  data_param {
    batch_size: 10
    backend: LMDB
  }
  op_transform_param {
    stride: 8
    max_degree_rotations: "45"
    crop_size_x: 368
    crop_size_y: 368
    center_perterb_max: 40
    center_swap_prob: 0
    scale_prob: 1
    scale_mins: "0.333333333333"
    scale_maxs: "1.5"
    target_dist: 0.6
    number_max_occlusions: "2"
    sigmas: "7.0"
    models: "COCO_18;COCO_18_18"
    sources: "/workspace/openpose_train/dataset/lmdb_coco"
    probabilities: "1.0"
    source_background: "/workspace/openpose_train/dataset/lmdb_background"
    prob_only_background: 0.02
    media_directory: ""
    normalization: 0
    add_distance: false
  }
}
