### ISSUE TITLE
Trasfer Learning

### ISSUE THREAD

**Issue by mrtechnoo** [CMU-Perceptual-Computing-Lab/openpose_train#44]
@gineshidalgo99  Is there any way to do transfer learning over the present model  preparing our own dataset. If so, how to prepare our own dataset is there any tutorial for that. Please let me know as it helps a lot for my project for my semester submission

**Comment by gineshidalgo99** [comment]
Sorry, not really a project we have worked on.

Still, I'd assume that simply re-using the OpenPose model as a backbone for your network is what you'd want to do transfer learning, that's what I'd try. (assuming the problems are related)

**Comment by gineshidalgo99** [comment]
Closing for not being an issue, but anybody is free to answer / continue the discussion!
