### ISSUE TITLE
why don't processing the last outputs with sigmoid activate function 

### ISSUE THREAD

**Issue by WillLiGitHub** [CMU-Perceptual-Computing-Lab/openpose_train#45]

**Comment by WillLiGitHub** [comment]
just thinding about it? and not test.

**Comment by gineshidalgo99** [comment]
This was 3 years ago, so I don't remember the details, but I believe the reasoning was either because sigmoid just gave worse accuracy or because due to the masking of non-labeled channels, sigmoid was an issue. But I no longer remember which one was, sorry!

**Comment by WillLiGitHub** [comment]
thanks a lot !!!
thers is an other question , why don't  use paramerable mask ?

**Comment by gineshidalgo99** [comment]
Just because I am not familiar with those, not sure of their cons/pros :)

**Comment by WillLiGitHub** [comment]
I'll try it, thanks again!!!
