### ISSUE TITLE
hand data lmdb problem

### ISSUE THREAD

**Issue by huangshaoguang** [CMU-Perceptual-Computing-Lab/openpose_train#6]
When I generate the hand lmdb data with CMU data(hand_labels、hand143_panopticdb), I get this problem. Is it the mask data must be needed?
Traceback (most recent call last):
  File "c_generateLmdbs.py", line 144, in <module>
    generateLmdbFile(sHandMpiiLmdbPath, sHandMpiiImagesFolder, sHandMpiiJsonFile, sCaffePythonPath, sHandMpiiMaskFolder)
  File "E:\openpose\openpose_train\training\generateLmdbFile.py", line 108, in generateLmdbFile
    raise Exception('Not found image: ' + maskMissFullPath)
Exception: Not found image: F:/dataset/CMUhand/COCO/cocoapi/images/mask2017/hand42/manual_train\000015774_01_l.png

**Comment by huangshaoguang** [comment]
Thank you for your sharing!

**Comment by gineshidalgo99** [comment]
Yes, it is. You can directly download the LMDB instead, that'd be faster.

**Comment by huangshaoguang** [comment]
Can you share the hand training code? I can't allways generate the code.
